# This build is used for public PR and CI builds.

trigger:
  batch: true
  branches:
    include:
    - main

schedules:
  # Ensure we build nightly to catch any new CVEs and report SDL often.
  - cron: "0 0 * * *"
    displayName: Nightly Build
    branches:
      include:
      - main
    always: true

pr:
  branches:
    include:
    - main

resources:
  repositories:
  - repository: 1es
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
  - template: /eng/ci/templates/variables/build.yml@self

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1es
  parameters:
    pool:
      name: 1es-pool-azfunc-public
      image: 1es-windows-2022
      os: windows
    sdl:
      codeql:
         compiled:
           enabled: true
         runSourceLanguagesInSourceAnalysis: true

    settings:
      # PR's from forks do not have sufficient permissions to set tags.
      skipBuildTagsForGitHubPullRequests: ${{ variables['System.PullRequest.IsFork'] }}

    stages:
    - stage: Build
      jobs:
      - template: /eng/ci/templates/jobs/build-artifacts.yml@self
        parameters:
          CreateArtifacts: false
